#######################################################################
#                                                                     #
#                        Makefile ( GNU make )                        #
#                                                                     #
######################################################################
TOP =../..
include $(TOP)/maketemp/files.mk

CPPSRC += ConeBeamCTSim.cpp
CCOPT  = -O2 -g -lstdc++
TARGET = tst

include $(TOP)/maketemp/default_host.mk